<?php

/**
 * @file
 * Contains dev_d8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dev_d8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dev_d8 module.
    case 'help.page.dev_d8':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Formation d8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dev_d8_theme() {
  return [
    'dev_d8' => [
      'render element' => 'children',
    ],
  ];
}
