editorial_block.editorial_block_entity_type.*:
  type: config_entity
  label: 'Editorial block type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
